class ConflictError(Exception):
    pass

class NotFoundError(Exception):
    pass